### PR TITLE
Allow passing icon to Pill component

### PR DESCRIPTION
**Pull request by witoszekdev**
I want to merge this so we can pass icons to Pill components (Chip from MUI)

### CODE REVIEW

**Comment by dominik-zeglen** [comment]
Mind adding a story for pills with icons?
I want to make sure it's properly styled and supported on our side.

**Comment by witoszekdev** [comment]
@dominik-zeglen done :)

**Review by orzechdev — APPROVED** [review]
What about small pills variant in storybook?

**Comment by witoszekdev** [comment]
@orzechdev I've added stories for small Pills as well

**Pull request merged**
